name: Clover:UI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build Packages
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Testbed App
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: r-ZMCm0zCIzr3oS9daTvXWRa1NYCJlQWy3RB7So71uI # this is bad bad but i have no access to secrets
          NETLIFY_SITE_ID: e79f255b-b622-448b-a490-8a39b1c6f72a
        with:
          args: deploy --dir=dist/packages/testbed --prod
